### ISSUE TITLE
AAPL计算MMT时遇到了没有close价格的日子

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/chstockbot#127]
aapl = Ticker('AAPL')
  aapl.load_data()
  aapl.get_price_lists()

1985/12/25日是假日，这时定投怎么投？

Traceback (most recent call last):
  File "/Users/hd/work/hdcola/chstockbot/stockutil/ticker.py", line 196, in <module>
    aapl.get_price_lists()
  File "/Users/hd/work/hdcola/chstockbot/stockutil/ticker.py", line 80, in get_price_lists
    df_w.append(df.loc[date, 'Close'])
  File "/usr/local/Caskroom/miniconda/base/envs/hddev/lib/python3.9/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/Caskroom/miniconda/base/envs/hddev/lib/python3.9/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/usr/local/Caskroom/miniconda/base/envs/hddev/lib/python3.9/site-packages/pandas/core/indexing.py", line 838, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/usr/local/Caskroom/miniconda/base/envs/hddev/lib/python3.9/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/usr/local/Caskroom/miniconda/base/envs/hddev/lib/python3.9/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/usr/local/Caskroom/miniconda/base/envs/hddev/lib/python3.9/site-packages/pandas/core/generic.py", line 3773, in xs
    loc = index.get_loc(key)
  File "/usr/local/Caskroom/miniconda/base/envs/hddev/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 704, in get_loc
    raise KeyError(orig_key) from err
KeyError: datetime.datetime(1985, 12, 25, 0, 0)

**Comment by hdcola** [comment]
现在考虑延后一天投
