### ISSUE TITLE
send_xyh.py运行时出错

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/chstockbot#139]
今天完蛋了，什么都不知道，快去通知管理员，bot已经废物了，出的问题是:
<class 'stockutil.ticker.TickerError'>:
TickerSPY里的历史数据没有200这么多
Traceback (most recent call last):
  File "/Users/hd/work/hdcola/chstockbot/sendxyh_new.py", line 75, in <module>
    ticker.cal_symbols_avg(ma)
  File "/Users/hd/work/hdcola/chstockbot/stockutil/ticker.py", line 136, in cal_symbols_avg
    raise TickerError(f"Ticker{self.symbol}里的历史数据没有{ma}这么多")
stockutil.ticker.TickerError: TickerSPY里的历史数据没有200这么多

**Comment by stephenzhu01** [comment]
取sma的时候raise了error，生成xyh msg的函数里面需要加一个if 判断一下。
