### ISSUE TITLE
发出了一个感觉不太对头的alert

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/chstockbot#151]
NDX AAPL输入的日期没有数据，请确保输入的日期当天有开市
SPX AAPL输入的日期没有数据，请确保输入的日期当天有开市
SPX OGN输入的日期没有数据，请确保输入的日期当天有开市

**Comment by hdcola** [comment]
config.json not found.Generate a new configuration file in /home/runner/work/chstockbot/chstockbot/config.json
9
  File "/home/runner/work/chstockbot/chstockbot/stockutil/index.py", line 88, in compare_avg_ma
10
    raise IndexError(f"{symbol.symbol}输入的日期没有数据，请确保输入的日期当天有开市")
11
stockutil.index.IndexError: AAPL输入的日期没有数据，请确保输入的日期当天有开市
12
Traceback (most recent call last):
13
  File "/home/runner/work/chstockbot/chstockbot/stockutil/index.py", line 88, in compare_avg_ma
14
    raise IndexError(f"{symbol.symbol}输入的日期没有数据，请确保输入的日期当天有开市")
15
stockutil.index.IndexError: AAPL输入的日期没有数据，请确保输入的日期当天有开市
16
Traceback (most recent call last):
17
  File "/home/runner/work/chstockbot/chstockbot/stockutil/index.py", line 88, in compare_avg_ma
18
    raise IndexError(f"{symbol.symbol}输入的日期没有数据，请确保输入的日期当天有开市")
19
stockutil.index.IndexError: OGN输入的日期没有数据，请确保输入的日期当天有开市

**Comment by hdcola** [comment]
https://github.com/hdcola/chstockbot/runs/3486090889?check_suite_focus=true

load ticker file['/home/runner/work/chstockbot/chstockbot/tests/data/nasdaq stocks/1/aapl.us.txt', '/home/runner/work/chstockbot/chstockbot/data/daily/us/nasdaq stocks/1/aapl.us.txt']

search时取到了test的数据。
